import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";

const animate = require("tailwindcss-animate");

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.vue",
    ],

    theme: {
        extend: {
            container: {
                center: true,
                padding: {
                    DEFAULT: "1rem",
                    md: "1.5rem",
                    lg: "2rem",
                    "2xl": "3rem",
                },
                screens: {
                    sm: "100%",
                    md: "100%",
                    lg: "1120px",
                    xl: "1280px",
                    "2xl": "1440px",
                },
            },
            backgroundImage: {
                footer: "url('/public/media/illustrations/footer.png')",
                home: "linear-gradient(180deg, #171A1B 20%, rgba(23, 26, 27, 0.90) 100%)",
                "box-course":
                    "linear-gradient(180deg, rgba(23, 26, 27, 0.00) 25%, rgba(23, 26, 27, 0.80) 70%, #171A1B 95%)",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                md: "0.375rem",
                lg: "0.5rem",
                xl: "0.75rem",
                "2xl": "1rem",
                "3xl": "1.5rem",
                full: "9999px",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: 0 },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: 0 },
                },
                "collapsible-down": {
                    from: { height: 0 },
                    to: { height: "var(--radix-collapsible-content-height)" },
                },
                "collapsible-up": {
                    from: { height: "var(--radix-collapsible-content-height)" },
                    to: { height: 0 },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                "collapsible-down": "collapsible-down 0.2s ease-in-out",
                "collapsible-up": "collapsible-up 0.2s ease-in-out",
            },
            fontSize: {
                xxs: ".625rem",
                xs: ".75rem",
                sm: ".875rem",
                base: "1rem",
                lg: "1.125rem",
                xl: "1.25rem",
                "xl-plus": "1.3125rem",
                "2xl": "1.5rem",
                "2xl-plus": "1.75rem",
                "3xl": "1.875rem",
                "3xl-plus": "2rem",
                "4xl": "2.25rem",
                "4xl-plus": "2.3125rem",
                "5xl": "3rem",
                "5xl-plus": "3.0625rem",
                "6xl": "4rem",
                "6xl-plus": "4.5rem",
                "7xl": "5rem",
                "8xl": "6rem",
                "9xl": "8rem",
            },
            colors: {
                white: "var(--white)",
                primary: {
                    DEFAULT: "var(--primary)",
                    surface: "var(--primary-surface)",
                    border: "var(--primary-border)",
                    hover: "var(--primary-hover)",
                    pressed: "var(--primary-pressed)",
                    focus: "var(--primary-focus)",
                },
                secondary: {
                    DEFAULT: "var(--secondary)",
                    surface: "var(--secondary-surface)",
                    border: "var(--secondary-border)",
                    hover: "var(--secondary-hover)",
                    pressed: "var(--secondary-pressed)",
                    focus: "var(--secondary-focus)",
                },
                neutral: {
                    10: "var(--neutral-10)",
                    20: "var(--neutral-20)",
                    30: "var(--neutral-30)",
                    40: "var(--neutral-40)",
                    50: "var(--neutral-50)",
                    60: "var(--neutral-60)",
                    70: "var(--neutral-70)",
                    80: "var(--neutral-80)",
                    90: "var(--neutral-90)",
                    100: "var(--neutral-100)",
                },
                red: {
                    100: "var(--red-100)",
                    200: "var(--red-200)",
                    300: "var(--red-300)",
                    400: "var(--red-400)",
                    500: "var(--red-500)",
                    600: "var(--red-600)",
                    700: "var(--red-700)",
                    800: "var(--red-800)",
                    900: "var(--red-900)",
                },
                yellow: {
                    100: "var(--yellow-100)",
                    200: "var(--yellow-200)",
                    300: "var(--yellow-300)",
                    400: "var(--yellow-400)",
                    500: "var(--yellow-500)",
                    600: "var(--yellow-600)",
                    700: "var(--yellow-700)",
                    800: "var(--yellow-800)",
                    900: "var(--yellow-900)",
                },
                green: {
                    100: "var(--green-100)",
                    200: "var(--green-200)",
                    300: "var(--green-300)",
                    400: "var(--green-400)",
                    500: "var(--green-500)",
                    600: "var(--green-600)",
                    700: "var(--green-700)",
                    800: "var(--green-800)",
                    900: "var(--green-900)",
                },
                blue: {
                    100: "var(--blue-100)",
                    200: "var(--blue-200)",
                    300: "var(--blue-300)",
                    400: "var(--blue-400)",
                    500: "var(--blue-500)",
                    600: "var(--blue-600)",
                    700: "var(--blue-700)",
                    800: "var(--blue-800)",
                    900: "var(--blue-900)",
                },
                indigo: {
                    100: "var(--indigo-100)",
                    200: "var(--indigo-200)",
                    300: "var(--indigo-300)",
                    400: "var(--indigo-400)",
                    500: "var(--indigo-500)",
                    600: "var(--indigo-600)",
                    700: "var(--indigo-700)",
                    800: "var(--indigo-800)",
                    900: "var(--indigo-900)",
                },
                purple: {
                    100: "var(--purple-100)",
                    200: "var(--purple-200)",
                    300: "var(--purple-300)",
                    400: "var(--purple-400)",
                    500: "var(--purple-500)",
                    600: "var(--purple-600)",
                    700: "var(--purple-700)",
                    800: "var(--purple-800)",
                    900: "var(--purple-900)",
                },
                pink: {
                    100: "var(--pink-100)",
                    200: "var(--pink-200)",
                    300: "var(--pink-300)",
                    400: "var(--pink-400)",
                    500: "var(--pink-500)",
                    600: "var(--pink-600)",
                    700: "var(--pink-700)",
                    800: "var(--pink-800)",
                    900: "var(--pink-900)",
                },
                gray: {
                    100: "var(--gray-100)",
                    200: "var(--gray-200)",
                    300: "var(--gray-300)",
                    400: "var(--gray-400)",
                    500: "var(--gray-500)",
                    600: "var(--gray-600)",
                    700: "var(--gray-700)",
                    800: "var(--gray-800)",
                    900: "var(--gray-900)",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            fontFamily: {
                gabarito: ["Gabarito", "sans-serif"],
            },
        },
    },

    plugins: [forms, animate],
};
